### ISSUE TITLE
pg_tde_set_master_key() functions creates invalid segment number 0 in file name upon pg_checksums utility

### ISSUE THREAD

**Issue by shahidullah79** [percona/pg_tde#162]
pg_checksums throws following error message when pg_tde_set_master_key() function calls.
pg_checksums: error: invalid segment number 0 in file name "/tmp/primary/base/16537/pg_tde.map"

**Steps to reproduce the issue**
_initdb --data-checksums -D /tmp/primary 
pg_ctl -D /tmp/primary -l logfile -o "-p 5434" start
psql -p 5434
create database db_tde;
\c db_tde
create extension pg_tde ;
SELECT pg_tde_add_key_provider_file('mk-file','/tmp/pg_tde_test_keyring.per');
SELECT pg_tde_set_master_key('test-db-master-key','mk-file');
\q_

Stop the server
_pg_ctl -D /tmp/primary -l /tmp/primary.log -o "-p 5434" stop

pg_checksums  -D /tmp/primary_
pg_checksums: error: invalid segment number 0 in file name "/tmp/primary/base/16537/pg_tde.map"

**Comment by ImTheKai** [comment]
Will be tracked here https://perconadev.atlassian.net/browse/PG-822
